# Generated by Django 4.0.6 on 2022-10-30 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_news_views_alter_news_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='опубліковано'),
        ),
    ]
